### ISSUE TITLE
[หน้า profile] ใน figma ไม่มีปุ่ม ออกจากระบบในหน้า profile

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#18]
1. ใน figma ไม่มีปุ่ม ออกจากระบบในหน้า profile

![IMG_7610](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/e266a643-bcf4-4e4b-aeee-37dcb7eaf223)

**Comment by pbenzyk** [comment]
ออกจากระบบ For Test login.
