### ISSUE TITLE
[หน้าหลัก-กรณีอัปเดทข้อมูลทั้งหมดแล้ว] คำหาย & รูปไม่เต็มวงกลม

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#21]
1. ไม่มีในส่วนของ **อัพเดตล่าสุด เมื่อไม่กี่นาทีก่อน** ตาม figma
2. รูปไม่เต็มวงกลม

![IMG_7614](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/79b694c9-2769-4473-8bb7-8f35f265c766)

[figma]

<img width="336" alt="image" src="https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/ec4414c2-6360-45ce-a903-9097a88c829e">

**Comment by bbun0639** [comment]
ตอนนี้ยังไม่มีอัพเดทข้อความล่าสุดครับ หน้านี้ค่อนข้างช้าอยู่แล้ว handle state มากเกินไป 
- แต่มีปรับปรับขนาดรูปภาพให้เต็มวงแล้ว

**Comment by bbun0639** [comment]
ตอนนี้ยังไม่มีอัพเดทข้อความล่าสุดครับ handle state มากเกินไป กลัวว่าจะทำให้หน้านี้ช้าลง

- แต่มีปรับปรับขนาดรูปภาพให้เต็มวงเรียบร้อยแล้ว
