### ISSUE TITLE
[หน้าสร้างโปรไฟล์ทีม] ตอนสร้างโปรไฟล์ทีม ถ้ายังไม่กดปันทึก ปุ่ม **ดูในมุมมองสาธารณะ** ไม่สามารถกดได้

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#27]
1. ตอนสร้างโปรไฟล์ทีม ถ้ายังไม่กดปันทึก ปุ่ม **ดูในมุมมองสาธารณะ** ไม่สามารถกดได้

![IMG_7624](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/63dbf930-1f10-4c84-b9a2-4c2ccde90772)

**Comment by bbun0639** [comment]
ปุ่มนี้จะกดได้เพื่อดู Preview ก่อนการ Submit อยู่แล้ว เป็นเหมือนกับทั้ง บุคคล / ทีมงาน / บริษัท เลยครับ
