### ISSUE TITLE
หน้าโปรไฟล์ทีม ได้ถูกอัพโหลดเรียบร้อยหาย

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#31]
หน้านี้ไม่มี ซึ่งหลังจากกดบันทึกสร้างทีมแล้วจะต้องไปหน้านี้

<img width="280" alt="image" src="https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/21f8af9e-12a3-41f6-9f1b-3db24a25276a">

**Comment by bbun0639** [comment]
FYI: The first time that you create a new team, this page will show up just once.
