### ISSUE TITLE
[คำถาม] ข้อมูลตอนสร้างบริษัทไม่มีให้ใส่ที่อยู่ แต่ในหน้า jobs - tab บริษัท ทำไมถึงมีจังหวัด

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#36]
[คำถาม] ข้อมูลตอนสร้างบริษัทไม่มีให้ใส่ที่อยู่ แต่ในหน้า jobs - tab บริษัท ทำไมถึงมีจังหวัด

![IMG_7639](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/8319606e-b4ee-4100-a94c-c5798a920602)

**Comment by bbun0639** [comment]
ที่อยู่บริษัทมีการเพิ่มมาในภายหลังครับ "Bkk" เป็นการ Mock ข้อมูลจากทีม Dev เอง ในส่วนนี้มี Field ที่อยู่ของบริษัทใต้ Field ชื่อบริษัท 
โดยจะต้องใส่เป็น Format Address
