### ISSUE TITLE
flow ในส่วนของ filter หน้า jobs ค่อนข้าง งง

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#37]
flow ในส่วนของ filter หน้า jobs ค่อนข้าง งง

![IMG_7640](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/78b79a62-31fe-4576-a65c-ec99d3233f90)

**Comment by bbun0639** [comment]
เปลี่ยนไอคอน และหัวข้อเป็น Search & Filter Jobs แทน ref:https://github.com/100xubn/ubn-app-issue-tracking/issues/39
