### ISSUE TITLE
[หน้า jobs] ปุ่มค้นหาหาย

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#39]
ปุ่มค้นหาหาย

![IMG_7656](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/40b32b55-08c3-48ac-8b9d-323688f634f7)

**Comment by pbenzyk** [comment]
ย้ายไปอยู่ใน filter

**Comment by bbun0639** [comment]
เปลี่ยน Icon: Filter -> Search
