### ISSUE TITLE
[หน้าแบบสอบถาม] คำเกิน, สีตัวหนังสือผิด, หน้าไม่เต็มหน้า

### ISSUE THREAD

**Issue by tarro55** [100xubn/ubn-app-issue-tracking#5]
1. title คำว่า **UncleBen Survey** ไม่มีในหน้านี้
2. คำว่า **ให้เราได้รู้จักคุณมากขึ้นในเวลาไม่เกิน 3 นาที** ตัวหนังสือต้องเป็นสีดำ
3. **UncleBen** ข้างล่างรูปต้องเว้นวรรคเป็น **Uncle Ben**
4. หน้าไม่เต็มหน้า มีขอบสีน้ำเงินขึ้นมา

![IMG_7595](https://github.com/100xubn/ubn-app-issue-tracking/assets/33993571/c8b04d6f-1d9e-4755-abcd-a40e060b2496)

**Comment by bbun0639** [comment]
FYI: หน้าไม่เต็มหน้าเป็น Safe Area View ของ Device ตั้งแต่ iPhone X ขึ้นไป หากเป็น iPhone SE, iPhone 8 หรือ Device Android จะเต็มปกติ
